### PR TITLE
Enable aarch64 support in Linux

### PR DESCRIPTION
**Pull request by andfoy**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by andfoy** [comment]
@conda-forge-admin, please re-render

**Comment by andfoy** [comment]
@duncanmmacleod , this one is ready to merge

**Comment by andfoy** [comment]
@isuruf, this package is required to continue working on the Qt 5.15 update, is it possible to have it merged?

**Comment by isuruf** [comment]
Let's give @duncanmmacleod more time to review.

**Comment by duncanmmacleod** [comment]
Sorry for the delay, I'm in and out of the office through September. Looks great, thanks @andfoy.

**Pull request merged**
